application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: '86400000'  # 24 hours in milliseconds
      refresh-token:
        expiration: '604800000'  # 7 days in milliseconds
      algorithm: HS256  # Specify the algorithm explicitly

spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update  # Update schema without dropping existing tables
    show-sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: yazoonzidan@gmail.com
    password: ozkn jrgh mmhd ebed  # Gmail App password
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            enable: false
          from: yazoonzidan@gmail.com  # Explicitly specify the "from" address
  servlet:
    multipart:
      max-file-size: 10MB
      enabled: true
      max-request-size: 10MB
  datasource:
    url: jdbc:mysql://localhost:3306/graduation_project3
    username: root
    password:  # No password for the database
    driver-class-name: com.mysql.cj.jdbc.Driver
  web:
    resources:
      cache:
        period: 0
  jackson:
    time-zone: UTC  # Ensure consistent timezone handling
  cache:
    type: simple  # Basic cache for small projects; use `redis` for production
    cache-names: userCache, appointmentCache  # Define cache names

file:
  upload-dir: user-photos/
  allowed-extensions: jpg,jpeg,png  # Restrict allowed file extensions



logging:
  level:
    com:
      example: DEBUG
    root: INFO
#  file:
#    name: logs/application.log  # Log output file


server:
  port: ${PORT:8080}

profiles:
  active: ${SPRING_PROFILES_ACTIVE:dev}  # Default to "dev" if not explicitly set

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics  # Enable health and info endpoints for monitoring

swagger:
  enabled: true
  base-package: com.example.GraduationProject.WebApi  # Adjust to your base package
  title: "Graduation Project API"
  description: "API documentation for the Graduation Project"
  version: "1.0.0"
  contact:
    name: "Support Team"
    email: "support@example.com"
    url: "https://example.com"

timezone: UTC  # Set the default timezone
